name: openfoamAgent
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    # 最小核心依赖 - 进一步精简
    - langchain-core==0.3.34
    - langgraph==0.2.71
    - langsmith==0.3.8
    - openai==1.61.1
    - anthropic==0.45.2
    - pydantic==2.10.6
    - python-dotenv==1.0.1
    - requests==2.32.3
    - numpy==2.2.2
    - pyyaml==6.0.2
    # API包装器依赖
    - uvicorn==0.24.0
    - fastapi==0.104.0